version: "3"
services:
  myportfolio:
    build: .
    restart: always
    env_file:
      - .env
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    image: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mydatabase:/var/lib/mysql

nginx:
    image: jonasal/nginx-certbot
    container_name: nginx
    restart: unless-stopped
    environment:
      - CERTBOT_EMAIL=juanpimod@gmail.com
      - CERTBOT_DOMAINS=jp-verse.duckdns.org,facturador.duckdns.org
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /root/nginx_confs:/etc/nginx/conf.d
      - /root/nginx_confs/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - webnet
volumes:
  mydatabase:
  nginx_secrets:

networks:
  default:
    name: webnet